version: '3.8'

volumes:
  postgres:
    driver: local
  # mysql:
  #   driver: local

services:
  postgres:
    image: postgres:15-alpine
    ports:
      - 5436:5432
    environment:
      - POSTGRES_DB=x-claim
      - POSTGRES_USER=x-claim
      - POSTGRES_PASSWORD=x-claim
    volumes:
      - postgres:/var/lib/postgresql/data/

  # mysql:
  #   image: mysql:8.0
  #   cap_add:
  #     - SYS_NICE
  #   restart: always
  #   environment:
  #     - MYSQL_DATABASE=x-claim
  #     - MYSQL_USER=x-claim
  #     - MYSQL_PASSWORD=x-claim
  #     - MYSQL_ROOT_PASSWORD=x-claim
  #   ports:
  #     - 3306:3306
  #   volumes:
  #     - mysql:/var/lib/mysql
