version: '3.9'

volumes:
  db:
  service-files:

services:
  service:
    image: gpproton/x-claim:latest
    restart: unless-stopped
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    environment:
      USER_SECRETS_ID: 836b9b8b-fd89-4aff-9286-809bda60998f
      ROOT_URI: "http://localhost:8000"
      # postgres | mysql | sqlite
      DB_TYPE: postgres
      DB_CONNECTION_STRING: "host=postgres_image;port=5432;database=x-claim;username=x-claim;password=x-claim"
      ASPNETCORE_URLS: "https://+:443;http://+:80"
#      ASPNETCORE_Kestrel__Certificates__Default__Password: dev
#      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/aspnetapp.pfx
    volumes:
      - service-files:/app/StaticFiles/
      - ~/.aspnet/https:/https:ro
      - ./secret.json:"/root/.microsoft/usersecrets/${USER_SECRETS_ID}/secret.json:ro"
    deploy:
      mode: replicated
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 64M

  db:
    image: postgres:15-alpine
    restart: unless-stopped
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "45432:5432"
    environment:
      POSTGRES_USER: x-claim
      POSTGRES_PASSWORD: x-claim
      POSTGRES_DB: x-claim
    deploy:
      mode: replicated
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 64M
