global using System.Collections;
global using System.Collections.ObjectModel;
global using CommunityToolkit.Mvvm.ComponentModel;
global using CommunityToolkit.Mvvm.Input;
global using CommunityToolkit.Maui.Markup;
global using CommunityToolkit.Maui.Views;
global using static CommunityToolkit.Maui.Markup.GridRowsColumns;
global using FA = UraniumUI.Icons.FontAwesome;
global using XClaim.Mobile.Extensions;
global using Maui.BindableProperty.Generator.Core;
global using XClaim.Mobile.Handlers;
global using XClaim.Mobile.Models;
global using XClaim.Mobile.ViewModel;
